# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cefc9f0f366c53a6dcafcbe1c3e39a06"
name = "productapp"
handle = "productapp-39"
application_url = "https://ending-blanket-leon-electoral.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://ending-blanket-leon-electoral.trycloudflare.com/auth/callback", "https://ending-blanket-leon-electoral.trycloudflare.com/auth/shopify/callback", "https://ending-blanket-leon-electoral.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
